#!/bin/bash

# This script should make api call to Pokémon APi and fetch data for Pokémon Pikachu
# The script should save success response to data.json as json
# Save failure response to errors.txt as a text

# Define the variable
URL="https://pokeapi.co/api/v2/pokemon/pikachu"
OUTPUT_FILE="data.json"
ERRORS_FILE="errors.txt"

# make the api call
curl -s -o "$OUTPUT_FILE" -w "%{http_code}" "$URL" > status_code.txt

# Get the status code from the response
STATUS_CODE=$(cat status_code.txt)
rm status_code.txt # cleanup

if [ "$STATUS_CODE" -eq 200 ]; then
    echo "Successfully fetched pikachu data"
else
    echo "Request failed with status: $STATUS_CODE" | tee "$ERRORS_FILE"
fi





