#!/bin/bash

# The script should extrsct the pokemon name, weight, and height from data.json
# The ooutput should be in human readable "Pikachu is of type Electric, weights, kg, and is 0.4m tall."

# file that contains pokemon data
DATA_FILE="data.json"

# Extract fileds from json using jq
name=$(jq -r '.name' "$DATA_FILE")
height=$(jq -r '.height' "$DATA_FILE")
weight=$(jq -r '.weight' "$DATA_FILE")
type=$(jq -r '.types[0].type.name' "$DATA_FILE")


# convert the hight decimal to meter, weight hectogram to kilogram using sed
formatted_height=$(echo "$height" | awk '{print $1 / 10}')
formatted_weight=$(echo "$weight" | awk '{print $1 /10}')

# Capitalize the fist later of the name using sed
name=$(echo "$name" | gsed 's/.*/\u&/')
type=$(echo "$type" | gsed 's/.*/\u&/')


# Return with the format print and message
echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."


